using System;
using System.Collections.Generic;
using System.Text;

namespace Scripts
{
    public enum InputCode
    {
            Letter_A = 4,
            Letter_B = 5,
            Letter_C = 6,
            Letter_D = 7,
            Letter_E = 8,
            Letter_F = 9,
            Letter_G = 10,
            Letter_H = 11,
            Letter_I = 12,
            Letter_J = 13,
            Letter_K = 14,
            Letter_L = 15,
            Letter_M = 16,
            Letter_N = 17,
            Letter_O = 18,
            Letter_P = 19,
            Letter_Q = 20,
            Letter_R = 21,
            Letter_S = 22,
            Letter_T = 23,
            Letter_U = 24,
            Letter_V = 25,
            Letter_W = 26,
            Letter_X = 27,
            Letter_Y = 28,
            Letter_Z = 29,

            Number_1 = 30,
            Number_2 = 31,
            Number_3 = 32,
            Number_4 = 33,
            Number_5 = 34,
            Number_6 = 35,
            Number_7 = 36,
            Number_8 = 37,
            Number_9 = 38,
            Number_0 = 39,

            Return = 40,
            Escape = 41,
            Backspace = 42,
            Tab = 43,
            Space = 44,
            Minus = 45,
            Equals = 46,
            LeftBracket = 47,
            RightBracket = 48,
            Backslash = 49,

            Semicolon = 51,
            Apostrophe = 52,
            Grave = 53,
            Comma = 54,
            Period = 55,
            Slash = 56,
            Capslock = 56,

            F1 = 58,
            F2 = 59,
            F3 = 60,
            F4 = 61,
            F5 = 62,
            F6 = 63,
            F7 = 64,
            F8 = 65,
            F9 = 66,
            F10 = 67,
            F11 = 68,
            F12 = 69,

            PrintScreen = 70,
            ScrollLock = 71,
            Pause = 72,
            Insert = 73,
            Home = 74,
            PageUp = 75,
            Delete = 76,
            End = 77,
            PageDown = 78,
            Right = 79,
            Left = 80,
            Down = 81,
            Up = 82,

            NumLockClear = 83,

            KeyPad_Divide = 84,
            KeyPad_Multiply = 85,
            KeyPad_Minus = 86,
            KeyPad_Plus = 87,
            KeyPad_Enter = 88,
            KeyPad_1 = 89,
            KeyPad_2 = 90,
            KeyPad_3 = 91,
            KeyPad_4 = 92,
            KeyPad_5 = 93,
            KeyPad_6 = 94,
            KeyPad_7 = 95,
            KeyPad_8 = 96,
            KeyPad_9 = 97,
            KeyPad_0 = 98,
            KeyPad_Period = 99,

            NonUSBackslash = 100,

            Application = 101,
            Power = 102,

            KeyPad_Equals = 103,

            F13 = 104,
            F14 = 105,
            F15 = 106,
            F16 = 107,
            F17 = 108,
            F18 = 109,
            F19 = 110,
            F20 = 111,
            F21 = 112,
            F22 = 113,
            F23 = 114,
            F24 = 115,

            Execute = 116,
            Help = 117,
            Menu = 118,
            Select = 119,
            Stop = 120,
            Again = 121,
            Undo = 122,
            Cut = 123,
            Copy = 124,
            Paste = 125,
            Find = 126,
            Mute = 127,
            VolumeUp = 128,
            VolumeDown = 129,

            KeyPad_Comma = 133,
            KeyPad_EqualsAS400 = 134,

            International_1 = 135,
            International_2 = 136,
            International_3 = 137,
            International_4 = 138,
            International_5 = 139,
            International_6 = 140,
            International_7 = 141,
            International_8 = 142,
            International_9 = 143,
            Lang1 = 144,
            Lang2 = 145,
            Lang3 = 146,
            Lang4 = 147,
            Lang5 = 148,
            Lang6 = 149,
            Lang7 = 150,
            Lang8 = 151,
            Lang9 = 152,

            AltErase = 153,
            SysReq = 154,
            Cancel = 155,
            Clear = 156,
            Prior = 157,
            Return2 = 158,
            Separator = 159,
            Out = 160,
            Oper = 161,
            ClearAgain = 162,
            CrSel = 163,
            ExSel = 164,

            Keypad_00 = 176,
            Keypad_000 = 177,
            ThousandSeparator = 178,
            DecimalSeparator = 179,
            CurrencyUnit = 180,
            CurrencySubunit = 181,
            KeyPad_LeftParen = 182,
            KeyPad_RightParen = 183,
            KeyPad_LeftBrace = 184,
            KeyPad_RightBrace = 185,
            KeyPad_Tab = 186,
            KeyPad_Backspace = 187,
            KeyPad_A = 188,
            KeyPad_B = 189,
            KeyPad_C = 190,
            KeyPad_D = 191,
            KeyPad_E = 192,
            KeyPad_F = 193,
            KeyPad_XOR = 194,
            KeyPad_Power = 195,
            KeyPad_Less = 197,
            KeyPad_Greater = 198,
            KeyPad_Ampersand = 199,
            KeyPad_DBLAmpersand = 200,
            KeyPad_VerticalBar = 201,
            KeyPad_DBLVerticalBar = 202,
            KeyPad_Colon = 203,
            KeyPad_Hash = 204,
            KeyPad_Space = 205,
            KeyPad_At = 206,
            KeyPad_Exclamation = 207,
            KeyPad_MemStore = 208,
            KeyPad_MemRecall = 209,
            KeyPad_MemClear = 210,
            KeyPad_MemAdd = 211,
            KeyPad_MemSubtract = 212,
            KeyPad_MemMultiply = 213,
            KeyPad_MemDivide = 214,
            KeyPad_PlusMinus = 215,
            KeyPad_Clear = 216,
            KeyPad_ClearEntry = 217,
            KeyPad_Binary = 218,
            KeyPad_Octal = 219,
            KeyPad_Decimal = 220,
            KeyPad_Hexadecimal = 221,

            LCtrl = 224,
            LShift = 225,
            LAlt = 226,
            LGui = 227,
            RCtrl = 228,
            RShift = 229,
            RAlt = 230,
            RGui = 231,
            Mode = 257,

            AudioNext = 258,

            AudioPrev = 259,
            AudioStop = 260,
            AudioPlay = 261,
            AudioMute = 262,
            MediaSelect = 263,
            WWW = 264,
            Mail = 265,
            Calculator = 266,
            Computer = 267,
            AC_Search = 268,
            AC_Home = 269,
            AC_Back = 270,
            AC_Forward = 271,
            AC_Stop = 272,
            AC_Refresh = 273,
            AC_Bookmarks = 274,

            BrightnessDown = 275,
            BrightnessUp = 276,
            DisplaySwitch = 277,
            KBDillumToggle = 278,
            KBDillumDown = 279,
            KBDillumUp = 280,
            Eject = 281,
            Sleep = 282,
            App1 = 283,
            App2 = 284,

            AudioRewind = 285,
            AudioFastForward = 286,

            SoftLeft = 287,
            SoftRight = 288,
            Call = 289,
            EndCall = 290,

            NumKeyCodes = 512
    };


    public enum MouseButton
    {
        Left = 1,
        Middle = 2,
        Right = 3
    }

    public enum GamepadButton
    {
        South = 1,
        East = 2,
        West = 3,
        North = 4,
        Back = 5,
        Guide = 6,
        Start = 7,
        LeftStick = 8,
        RightStick = 9,
        LeftShoulder = 10,
        RightShoulder = 11,
        DpadUp = 12,
        DpadDown = 13,
        DpadLeft = 14,
        DpadRight = 15,
        Misc1 = 16,
        RightPaddle1 = 17,
        LeftPaddle1 = 18,
        RightPaddle2 = 19,
        LeftPaddle2 = 20,
        Touchpad = 21,
        Misc2 = 22,
        Misc3 = 23,
        Misc4 = 24,
        Misc5 = 25,
        Misc6 = 26
    }

    public enum GamepadAxis
    {
        LeftX = 1,
        LeftY = 2,
        RightX = 3,
        RightY = 4,
        LeftTrigger = 5,
        RightTrigger = 6,
    }
}
